---
- hosts: all
  become: yes
  gather_facts: true
  remote_user: root
  vars:
    - cantaloupe_build_from_custom_source: false
    - cantaloupe_version: 4.1.1
    - cantaloupe_properties_path: /opt/cantaloupe
    - tomcat8_java_opts:
      - -Dcantaloupe.config={{ cantaloupe_properties_path }}/cantaloupe.properties
      - -Xmx4g
    - cantaloupe_user: tomcat8
    - cantaloupe_group: tomcat8
    - cantaloupe_deploy_war: yes
    - cantaloupe_deploy_war_path: /opt/tomcat/webapps
    - cantaloupe_deploy_war_filename: cantaloupe
    - cantaloupe_admin_password: "admin"
    - cantaloupe_source_static: HttpSource
    - cantaloupe_HttpSource_BasicLookupStrategy_url_prefix: http://dlib.nyu.edu/files/books/

  roles:
    - java
    - tomcat
    - cantaloupe

  post_tasks:
    - block:
      - name: install required packages
        yum:
          name:
            - nano
            - git
            - maven
          state: latest
#      - name: clone Cantaloupe source
#        git:
#          repo: 'https://github.com/nyudlts/cantaloupe'
#          dest: /home/vagrant/cantaloupe/
#          version: 'feature/disableHttpAuth'
      - name: build Cantaloupe from source
        shell: "cd /vagrant/cantaloupe;mvn clean package -DskipTests"
        no_log: true
      - name: copy newly built .war to Tomcat webapps
        command: "cp /vagrant/cantaloupe/target/cantaloupe-4.1.1-SNAPSHOT.war /opt/tomcat/webapps/cantaloupe.war"
      - name: copy cantaloupe config file back
        copy:
          src: ../cantaloupe.properties
          dest: "{{ cantaloupe_properties_path }}"
          owner: "{{ cantaloupe_user }}"
          group: "{{ cantaloupe_user }}"
          mode: 0777
      - name: restart Tomcat service
        service:
          name: tomcat8
          state: restarted
        no_log: true
      when: cantaloupe_build_from_custom_source
