---
- name: Install epel
  yum: 
    name: epel-release
    state: latest

- name: Update
  yum:
    name: '*'
    state: latest

- yum:
    name: "python2-pip"
    state: present

- pip:
    name: pip
    state: latest
