---
- hosts: testing
  become: yes
  #gather_facts: true
  remote_user: root

  vars: 
    ntp_manage_config: true
    ntp_timezone: America/New_York
    firewall_state: started
    firewall_enabled_at_boot: true
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "443"
      - "8052"
      - "8080"
    firewall_additional_rules:
      - "iptables -A INPUT -p icmp -m comment --comment '000 accept all icmp' -j ACCEPT"
      - "iptables -A INPUT -i lo -m comment --comment '001 accept all to lo interface' -j ACCEPT"
      - "iptables -A INPUT -m comment --comment '003 accept related established rules' -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT"
      - "iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT"
      - "iptables -A INPUT -p icmp -j ACCEPT"
      - "iptables -A INPUT -i lo -j ACCEPT"
      - "iptables -A OUTPUT -o lo -j ACCEPT"
      - "iptables -A INPUT -m comment --comment '910 deny all other input requests' -j DROP"
    firewall_disable_firewalld: true
    solr_version: "6.5.0"
    solr_port: "8983"
    solr_timezone: "EST"
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "localhost"
        root: "/opt/solr"
        template: "{{ nginx_vhost_template }}"
        filename: "solr.conf"
        extra_parameters: |
          location / {
            proxy_pass http://localhost:8983;
          }

  roles:
    - housekeeping
    #- firewall
    - ntp
    - logrotate
    - java
    - nginx
    #- solr

